---

- name: "Wordpress Installation On LEMP-Stack"
  become: true
  hosts: all
  vars:
    nginx_port: 80
    nginx_user: "www-data"
    nginx_group: "www-data"
    domain_name: "www.domain.com"
    mysql_root: "mysqlroot123"
    mysql_user: "wordpress"
    mysql_password: "wordpress"
    mysql_database: "wordpress"
    wordpress_url: "https://wordpress.org/wordpress-5.7.2.tar.gz"
  tasks:
    
    - name: "nginx - Installing nginx php Webserver"
      apt:
        name:
        - nginx
        - php
        state: present
    
    
    - name: "nginx - Creating nginx Configuration File"
      template:
        src: nginx.conf.tmp1
        dest: /etc/nginx/nginx.conf
      
    
    - name: "nginx - Creating VirtualHost"
      template:
        src: virtualhost.conf.tmpl
        dest: "/etc/nginx/conf.d/{{ domain_name }}.conf"
            
            
    - name: "nginx - Creating VirtualHost DocumentRoot"
      file:
        path: "/var/www/html/{{ domain_name }}"
        state: directory 
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
            
            
    - name: "nginx - Creating test.php info file"
      copy:
        content: "<?php phpinfo(); ?>"
        dest: "/var/www/html/{{ domain_name }}/test.php"
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
            
    - name: "nginx - Restart/Enable Service"
      service:
        name: nginx
        state: restarted
        enabled: true
            
    - name: "MySQL - package Installation"
      yum:
        name: 
          - mysql-server
          - python-mysqldb
          - python3-mysqldb
        state: present
        update_cache: yes

    - name: "mysql - restarting/enabling service"
      service:
        name: mysql
        state: restarted
        enabled: true
            
    - name: "mysql - update root password"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        user: "root"
        password: "{{ mysql_root }}"
        host_all: true
            
    - name: "mysql - removing anonymous users"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        user: ""
        state: absent
            
    - name: "mysql - removing test database"
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        name: "test"
        state: absent
            
            
    - name: "mysql - creating database"
      mysql_db:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        name: "{{ mysql_database }}"
        state: present
            
    - name: "mysql - creating user & password"
      mysql_user:
        login_user: "root"
        login_password: "{{ mysql_root }}"
        user: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        host: "%"
        priv: '{{ mysql_database }}.*:ALL' 
            
    - name: "Wordpress - Downloading Tar File"
      get_url:
        url: "{{ wordpress_url }}"
        dest: /tmp/wordpress.tar.gz
            
    - name: "Wordpress - Extracting Wordpress.tar"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: true
            
    - name: "Wordpress - Copying Contents"
      copy:
        src: /tmp/wordpress/
        dest: "/var/www/html/{{  domain_name  }}/"
        remote_src: true
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
            
    - name: "Wordpress - Creating wp-config.php"
      template:
        src: wp-config.php.tmpl
        dest: "/var/www/html/{{  domain_name  }}/wp-config.php"
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
            
    
    - name: "Post-Installation Restart"
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nginx
        - mysql
        
    - name: "Post-Installation Clean-Up"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/wordpress
        - /tmp/wordpress.tar.gz
